project:
  type: website
  output-dir: docs

website:
  title: "Predictive Modeling"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: None
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



